### PR TITLE
Refactor ChooseTradingPair to use local state and then redirect

### PR DESCRIPTION
**Pull request by thomaseizinger**
This patch overhauls the whole logic of how the individual swap flows are mounted and works based off routes now. I left some TODOs in some of the other flows that needs a bit of follow-up work to pull all the props through.

Overall, I'd suggest that we move away from redux as much as possible and rely on component-local state + routes instead. Redux's global store introduces too much magic for my liking and makes it unpredictable, where a specific component gets its data from. This in turn makes it harder to see, how components could be composed together in a better way.

### CODE REVIEW

**Comment by tiero** [comment]
Will take a look ASAP, but would say that not a huge fan of mixing style/format changes and functional one. 

Can we split out in two separated PR? It makes also easier to review this refactor. Thanks

**Comment by thomaseizinger** [comment]
> Will take a look ASAP, but would say that not a huge fan of mixing style/format changes and functional one. 
> 
> Can we split out in two separated PR? It makes also easier to review this refactor. Thanks
> 
> 

Happy to split in two if you feel strongly. It is easy because I would just drop the last commit from this PR and open one on top of it.
Have you tried reviewing it commit-by-commit though? :)

**Comment by tiero** [comment]
Don't worry it's ok then, it's just me then I don't usually mix functional changes and style/format :) 

(ie. easy to revert/rollback if some regression happens)

**Comment by thomaseizinger** [comment]
> Don't worry it's ok then, it's just me then I don't usually mix functional changes and style/format, regardless of complexity :) 
> 
> (ie. easy to revert/rollback if some regression happens) 

Neither do I, they are all in separate commits :)
But given that it is so easy, I will split it in two PRs and then everyone is happy :D

**Comment by thomaseizinger** [comment]
New PR that only contains the refactoring is here: https://github.com/opendexnetwork/opendex.app/pull/44

**Review by tiero — APPROVED** [review]

**Comment by thomaseizinger** [comment]
@opendexnetwork/opendex-app Can someone with admin rights enable PR retargeting on this repo? I think it just needs "automatic deletion of head branches".

**Comment by thomaseizinger** [comment]
Had to do another force push for netlify to actually deploy this.

**Comment by maybeast** [comment]
> @opendexnetwork/opendex-app Can someone with admin rights enable PR retargeting on this repo? I think it just needs "automatic deletion of head branches".

Enabled.

**Comment by maybeast** [comment]
@thomaseizinger @tiero 

Added 2 minor commits:
- move PoweredBy (previously SwapProvider) component back to its original visual location
- add `redirects` file for netlify to support the new URLs

If you're OK with these changes we can get this merged. I'll add Boltz specific url support in a separate PR.

**Review by maybeast — APPROVED** [review]

**Comment by thomaseizinger** [comment]
I am okay with that (can't approve my own PR).

(1) was unintentional, sorry!

**Pull request merged**
