### PR TITLE
feat(boltz): implement rate fetcher interface

### PR DESCRIPTION
**Pull request by maybeast**
This is a WIP PR that implements the proposed rate fetcher interface for Boltz defined in https://github.com/opendexnetwork/opendex.app/pull/21

### CODE REVIEW

**Comment by tiero** [comment]
shall we merge #21 first? so I can unlock also #18

**Comment by maybeast** [comment]
> shall we merge #21 first? so I can unlock also #18 §
> 
> Ps. moving from private to public, break something and I cannot see the changes in the PR at the same height in my fork
> 
> it seems to miss [the latest commit ](https://github.com/tiero/opendex.app/commit/951dfefc386c0df11fa38a61dc5331a31925b27d) about decimal.js > bignumber.js

Yes, 100%. Wasn't planning on getting this in before the rate fetcher interface PR is merged.

**Comment by maybeast** [comment]
> it seems to miss [the latest commit ](https://github.com/tiero/opendex.app/commit/951dfefc386c0df11fa38a61dc5331a31925b27d) about decimal.js > bignumber.js

Rebased to latest now :).

**Comment by maybeast** [comment]
Rebased against current main branch.

**Comment by maybeast** [comment]
Closing this as it was included in https://github.com/opendexnetwork/opendex.app/pull/33

**Pull request closed without merging**
